version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    ports:
      - 27017:27017

  adm-azs-shipping:
    image: adm-azs-shipping:latest
    container_name: "adm-azs-shipping"
    build: .
    ports:
      - 9090:8080
    links:
      - mongo