version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: