services:
  - name: shipping-project
    env: docker
    buildCommand: docker-compose -f docker-compose.yml build
    startCommand: docker-compose -f docker-compose.yml up
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        fromService:
          name: mongo
          type: host
          port: 27017

  - name: mongo
    env: docker
    buildCommand: docker-compose -f docker-compose.yml build mongo
    startCommand: docker-compose -f docker-compose.yml up mongo