services:
  - name: mongo
    image: mongo
    ports:
      - 27017:27017

  - name: adm-azs-shipping
    buildCommand: docker build -t adm-azs-shipping .
    startCommand: docker-compose -f docker-compose.yml up
    env:
      - key: PORT
        value: "8080"